version: '2'

services:
    subscriber_a:
        container_name: subscriber_a
        image: ciena/subscriber
        environment:
        - WHO_AM_I=Subscriber-A
        cap_add:
        - ALL
        network_mode: none

    subscriber_b:
        container_name: subscriber_b
        image: ciena/subscriber
        environment:
        - WHO_AM_I=Subscriber-B
        cap_add:
        - ALL
        network_mode: none

    uplink:
        container_name: uplink
        image: ciena/subscriber
        cap_add:
        - ALL
        
    egress_vnf_a:
        container_name: egress_vnf_a
        image: ciena/vnf
        environment:
        - DEBUG=true

    egress_vnf_b_subscriber_a:
        container_name: egress_vnf_b_subscriber_a
        image: ciena/vnf
        environment:
        - DEBUG=true

    egress_vnf_b_subscriber_b:
        container_name: egress_vnf_b_subscriber_b
        image: ciena/vnf
        environment:
        - DEBUG=true

    egress_vnf_c:
        container_name: egress_vnf_c
        image: ciena/vnf
        environment:
        - DEBUG=true

    ingress_vnf_a:
        container_name: ingress_vnf_a
        image: ciena/vnf
        environment:
        - DEBUG=true

    ingress_vnf_b_instance_1:
        container_name: ingress_vnf_b_instance_1
        image: ciena/vnf
        environment:
        - DEBUG=true

    ingress_vnf_b_instance_2:
        container_name: ingress_vnf_b_instance_2
        image: ciena/vnf
        environment:
        - DEBUG=true

    ingress_vnf_b_instance_3:
        container_name: ingress_vnf_b_instance_3
        image: ciena/vnf
        environment:
        - DEBUG=true

    udp_service_subscriber_a:
        container_name: udp_service_subscriber_a
        image: ciena/udp-svc
        network_mode: none
        environment:
        - MESSAGE="UDP for subscriber A"

    udp_service_subscriber_b:
        container_name: udp_service_subscriber_b
        image: ciena/udp-svc
        network_mode: none
        environment:
        - MESSAGE="UDP for subscriber B"

    tcp_service_instance_1:
        container_name: tcp_service_instance_1
        image: ciena/tcp-svc
        network_mode: none
        cap_add:
        - ALL
        environment:
        - MESSAGE="TCP Service Instance 1"

    tcp_service_instance_2:
        container_name: tcp_service_instance_2
        image: ciena/tcp-svc
        network_mode: none
        cap_add:
        - ALL
        environment:
        - MESSAGE="TCP Service Instance 2"
